config/routes.rb
Rails.application.routes.draw do

  get 'members/list' => 'members#list'
  get 'members/success' => 'members#success'
  get 'members/mailing' => 'members#mailing'
  resources :members

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

  root 'members#new'

end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_action :login_required, except: [:new, :create, :success]
  before_action :login_required, :admin_required, except: [:new, :create, :success, :list]
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :statistics, only: [:index, :list, :mailing]

  # GET /members
  # GET /members.json
  def index
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  def mailing
  end

  def list
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to "/members/success", notice: @member.name+'的報名資料已經成功送出！' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  def success
    @members = Member.all
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:member).permit(:name, :title, :personal_id, :office_phone, :mobile_phone, :address, :email, :school, :person_type, :room_type, :room_partiner, :room_date, :food, :transportation, :car_id, :group)
    end

    def statistics

      @members = Member.all

      @food1 = Member.where("food=1")
      @food2 = Member.where("food=2")

      @msg = "目前總報名人數為" + @members.count.to_s + "人。<br />\n"
      @msg += "葷食" + @food1.count.to_s + "人，素食" + @food2.count.to_s + "人。<br /><br/>\n"


      @roomtype22 = Member.where("room_type=2 and room_date=2")
      @msg += "單人房(10/14)一天："+@roomtype22.count.to_s+"個房間<br />"
      @roomtype21 = Member.where("room_type=2 and room_date=1")
      @msg += "單人房(10/13、10/14)兩天："+@roomtype21.count.to_s+"個房間<br />"
      @roomtype32 = Member.where("(room_type=3 or room_type=4) and room_date=2")
      @msg += "雙人房(10/14)一天："+(@roomtype32.count/2).to_s+"個房間<br />"
      @roomtype31 = Member.where("(room_type=3 or room_type=4) and room_date=1")
      @msg += "雙人房(10/13、10/14)兩天："+(@roomtype31.count/2).to_s+"個房間<br /><br />"

      @trans2 = Member.where("transportation=2")
      @msg += "需備停車位："+@trans2.count.to_s+"個<br />"
      @trans3 = Member.where("transportation=3")
      @msg += "台鐵接送："+@trans3.count.to_s+"位<br />"
      @trans4 = Member.where("transportation=4")
      @msg += "臺中高鐵接送："+@trans4.count.to_s+"位<br />"
      @trans5 = Member.where("transportation=5")
      @msg += "嘉義高鐵接送："+@trans5.count.to_s+"位<br /><br />"

      @groupa = Member.where(group: [1,2])
      @msg += "分組討論A組優先："+@groupa.count.to_s+"個<br />"
      @groupb = Member.where(group: [3,4])
      @msg += "分組討論B組優先："+@groupb.count.to_s+"個<br />"
      @groupc = Member.where(group: [5,6])
      @msg += "分組討論C組優先："+@groupc.count.to_s+"個<br />"


    end

end

app/helpers/members_helper.rb
module MembersHelper

  def personTypeStr(num)
    case num
      when 1 then "神父"
      when 2 then "修女"
      when 3 then ""
    end
  end

  def roomTypeStr(num)
    case num
      when 1 then "自理"
      when 2 then "單人"
      when 3 then "雙人*"
      when 4 then "雙人"
    end
  end

  def roomDateStr(num)
    case num
      when 0 then "自理"
      when 1 then "兩天"
      when 2 then "一天"
    end
  end

  def foodStr(num)
    case num
      when 1 then ""
      when 2 then "素"
    end
  end


  def transportationStr(num)
    case num
      when 1 then "自行前往"
      when 2 then "自行前往*"
      when 3 then "台鐵"
      when 4 then "高鐵烏日"
      when 5 then "高鐵嘉義"
    end
  end

  def groupStr(num)
    case num
      when 1 then "A、B、C"
      when 2 then "A、C、B"
      when 3 then "B、A、C"
      when 4 then "B、C、A"
      when 5 then "C、A、B"
      when 6 then "C、B、A"
    end
  end

end

app/views/members/_form.html.erb
<h2>2015天主教學校經營領導研習營</h2>

<%= simple_form_for @member, :html=>{:class=>'form-horizontal'} do |f| %>

    <% if @member.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

          <ul>
            <% @member.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-4 well well-sm">
        <legend><i class="glyphicon glyphicon-globe"></i> 新增報名資料</legend>
        <form action="#" method="post" class="form" role="form">
          <div class="row">
            <div class="col-xs-6 col-md-6">
              <%= f.input :name, :label=>false, :autofocus=>true,:placeholder=>"姓名",:required=>true %><br>
            </div>
            <div class="col-xs-6 col-md-6">
              <%= f.input :personal_id, :placeholder=>"身份證字號", :required=>true,:label=>false %>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-6 col-md-6">
              <%= f.input :school, :placeholder=>"就職學校", :required=>true,:label=>false %>
            </div>
            <div class="col-xs-6 col-md-6">
              <%= f.input :title, :label=>false, :placeholder=>"職稱",:required=>true %><br>
            </div>
            <div class="col-xs-6 col-md-6">
              <%= f.input :office_phone, :placeholder=>"辦公室電話", :required=>false,:label=>"格式05-1234567#123" %>
            </div>
            <div class="col-xs-6 col-md-6">
              <% f.input :mobile_phone, :placeholder=>"手機號碼", :input_html=>{:pattern=>"^[0][1-9]{1,3}[-][0-9]{6,8}$"}, :required=>true,:label=>"格式0912-345678" %>
              <%= f.input :mobile_phone, :placeholder=>"手機號碼", :required=>true, :label=>"格式0912-345678" %>
            </div>

          </div>

          <div class="row">

          </div>

          <%= f.input :email, :placeholder=>"電子信箱",:required=>true,:type=>"email",:label=>false %>
          <br />
          <%= f.input :person_type,:prompt=>"請選擇身份別",:input_html=>{:required=>true},:collection=>{"神父（共祭者煩請自備大白衣及白色領帶）"=>1,"修女"=>2,"非神職人員"=>3},:label=>false %>

          <%= f.input :room_type,:prompt=>"請選擇住宿選項",:input_html=>{:required=>true},:collection=>{"自理"=>1,"單人套房（1600元）"=>2,"雙人套房（900元，自行填寫共住夥伴）"=>3,"雙人住宿（900元，由主辦單位安排共住夥伴）"=>4},:label=>false %>
          <%= f.input :room_partiner, :input_html=>{:placeholder=>"指定共住夥伴姓名（留空白則由主辦單位安排）", :required=>false},:label=>false %>
          <%= f.input :room_date, :prompt=>"選擇住宿日期", :input_html=>{:required=>true},:collection=>{"自理"=>0,"10/13~14住宿兩天"=>1,"10/14住宿一天"=>2},:label=>false %>

          <%= f.input :food, :prompt=>"選擇餐食", :input_html=>{:required=>true},:collection=>{"葷食"=>1,"素食"=>2},:label=>false %>

        
          <%= f.input :transportation,:prompt=>"請選擇交通工具",:input_html=>{:required=>true},
                      :collection=>{"自行前往不需停車位"=>1,"自行前往需備停車位"=>2,"搭乘台鐵至斗六站由正心接送（09:00後站出口）"=>3,
                                    "搭乘高鐵至台中烏日站由正心接送（08:30於6號出口）"=>4,"搭乘高鐵至嘉義站由正心接送（08:45於一樓大廳）"=>5},:label=>false %>


          <%= f.input :group,:prompt=>"請選擇分組討論組別志願序",:input_html=>{:required=>true},
                      :collection=>{"A、B、C"=>1,"A、C、B"=>2,"B、A、C"=>3,"B、C、A"=>4,"C、A、B"=>5,"C、B、A"=>6}, :label=>false %>


          <br />
          <br />
          <%= f.button :submit, "送出報名資料", :class=>"btn btn-lg btn-block" %>


        </form>
      </div>
    </div>


<% end %>

app/views/members/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "管理者選單", members_path, :class=>"navbar-brand" %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to "修改管理者帳號", users_path %></li>
        <li><%= link_to "產生郵件清單", members_mailing_path %></li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">排序依據<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">依報名順序</a></li>
            <li><a href="#">依姓名</a></li>
            <li><a href="#">依學校</a></li>
            <li><a href="#">依討論組別</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">上面這些功能還沒設計好</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">請勿使用</a></li>
          </ul>
        </li>
      </ul>


      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "登出", "/logout", method: :delete, data: { confirm: '你確定要登出嗎？' } %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/members/edit.html.erb
<h2>編輯報名資料</h2>

<%= render 'form' %>

<%= link_to '顯示', @member, :class=>'btn btn-primary' %> |
<%= link_to '返回', members_path, :class=>'btn btn-primary' %>

app/views/members/index.html.erb
<%= render 'navbar' %>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">各項統計資料</h3>
  </div>
  <div class="panel-body">
    <%= @msg.html_safe %>
  </div>
</div>


<h2>印出所有已報名清單</h2>

<table class="table table-bordered" style="white-space: nowrap">
  <thead>
    <tr>
      <th>序號</th>
      <th>姓名</th>
      <th>學校</th>
      <th>職稱</th>
      <th>身份證字號</th>
      <th>市話</th>
      <th>手機</th>
      <th>電子郵件</th>
      <th>身份別</th>
      <th>住宿房間</th>
      <th>共住夥伴</th>
      <th>住宿日期</th>
      <th>餐食</th>
      <th>交通工具</th>
      <th>分組討論</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.id %></td>
        <td><%= member.name %></td>
        <td><%= member.school %></td>
        <td><%= member.title %></td>
        <td><%= member.personal_id %></td>
        <td><%= member.office_phone %></td>
        <td><%= member.mobile_phone %></td>
        <td><%= member.email %></td>
        <td><%= personTypeStr(member.person_type) %></td>
        <td><%= roomTypeStr(member.room_type) %></td>
        <td><%= member.room_partiner %></td>
        <td><%= roomDateStr(member.room_date) %></td>
        <td><%= foodStr(member.food) %></td>
        <td><%= transportationStr(member.transportation) %></td>
        <td><%= groupStr(member.group) %></td>
        <td><%= link_to '顯示', member %></td>
        <td><%= link_to '編輯', edit_member_path(member) %></td>
        <td><%= link_to '刪除', member, method: :delete, data: { confirm: '你確定要刪除嗎？本動作無法復原！' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '建立新報名資料', new_member_path, :class=>'btn btn-primary' %>

app/views/members/list.html.erb
<%= current_user.name %>：<br /> 歡迎光臨管理介面，可<%= link_to "點此登出", "/logout", method: :delete, data: { confirm: '你確定要登出嗎？' }, :class=>"btn btn-warning" %> 。

<br /><br />

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">各項統計資料</h3>
  </div>
  <div class="panel-body">
    <%= @msg.html_safe %>
  </div>
</div>


<h2>印出所有已報名清單</h2>

<table class="table table-bordered" style="white-space: nowrap">
  <thead>
    <tr>
      <th>序號</th>
      <th>姓名</th>
      <th>學校</th>
      <th>職稱</th>
      <th>身份證</th>
      <th>市話</th>
      <th>手機</th>
      <th>電子郵件</th>
      <th>身份別</th>
      <th>住宿房間</th>
      <th>共住夥伴</th>
      <th>住宿日期</th>
      <th>餐食</th>
      <th>交通工具</th>
      <th>分組討論</th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.id %></td>
        <td><%= member.name %></td>
        <td><%= member.school %></td>
        <td><%= member.title %></td>
        <td>*****</td>
        <td><%= member.office_phone %></td>
        <td><%= member.mobile_phone %></td>
        <td><%= member.email %></td>
        <td><%= personTypeStr(member.person_type) %></td>
        <td><%= roomTypeStr(member.room_type) %></td>
        <td><%= member.room_partiner %></td>
        <td><%= roomDateStr(member.room_date) %></td>
        <td><%= foodStr(member.food) %></td>
        <td><%= transportationStr(member.transportation) %></td>
        <td><%= groupStr(member.group) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '建立新報名資料', new_member_path, :class=>'btn btn-primary' %>

app/views/members/mailing.html.erb
<%= render 'navbar' %>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">郵件清單（複製貼入gmail收件人欄位即可）</h3>
  </div>
  <div class="panel-body">


    <% @members.each do |member| %>
        <%= member.name %><%= member.title %> &lt;<%= member.email %>&gt;,<br />
    <% end %>

  </div>
</div>

app/views/members/new.html.erb
<%= render 'form' %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>姓名:</strong>
  <%= @member.name %>
</p>

<p>
  <strong>身份證字號:</strong>
  <%= @member.personal_id %>
</p>

<p>
  <strong>學校:</strong>
  <%= @member.school %>
</p>

<p>
  <strong>職稱:</strong>
  <%= @member.title %>
</p>


<p>
  <strong>辦公室電話:</strong>
  <%= @member.office_phone %>
</p>

<p>
  <strong>手機號碼:</strong>
  <%= @member.mobile_phone %>
</p>

<p>
  <strong>電子郵件:</strong>
  <%= @member.email %>
</p>


<p>
  <strong>身份別:</strong>
  <%= @member.person_type %>
</p>

<p>
  <strong>房間型態:</strong>
  <%= @member.room_type %>
</p>

<p>
  <strong>共住夥伴:</strong>
  <%= @member.room_partiner %>
</p>

<p>
  <strong>住宿日期:</strong>
  <%= @member.room_date %>
</p>

<p>
  <strong>餐食:</strong>
  <%= @member.food %>
</p>

<p>
  <strong>交通方式:</strong>
  <%= @member.transportation %>
</p>

<p>
  <strong>分組討論志願序:</strong>
  <%= @member.group %>
</p>

<%= link_to '編輯', edit_member_path(@member),:class=>'btn btn-primary' %> |
<%= link_to '返回', members_path, :class=>"btn btn-primary" %>

app/views/members/success.html.erb
<p id="notice"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> <%= notice %></p>

<p>
  多謝您的報名，研習當天見！
</p>
<br />

<table class="table table-bordered" style="white-space: nowrap">
  <thead>
  <tr>
    <th>序號</th>
    <th>姓名</th>
    <th>學校</th>
    <th>職稱</th>
    <th>身份別</th>
    <th>餐食</th>
    <th>交通工具</th>
    <th>分組討論</th>
  </tr>
  </thead>

  <tbody>
  <% @members.each do |member| %>
      <tr>
        <td><%= member.id %></td>
        <td><%= member.name %></td>
        <td><%= member.school %></td>
        <td><%= member.title %></td>
        <td><%= personTypeStr(member.person_type) %></td>
        <td><%= foodStr(member.food) %></td>
        <td><%= transportationStr(member.transportation) %></td>
        <td><%= groupStr(member.group) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>